import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import { DurableObservabilityPipeline } from '../src/durable-observability.js';

test('records correlated events with sequence and integrity',async()=>{const p=new DurableObservabilityPipeline({sourceId:'worker-a'});const a=await p.record({id:'e1',type:'execution.started',executionId:'x',missionId:'m'},{traceId:'t',spanId:'s1'});const b=await p.record({id:'e2',type:'execution.completed',executionId:'x',missionId:'m'},{traceId:'t',spanId:'s2',parentSpanId:'s1'});assert.equal(a.state,'accepted');assert.equal(b.event.sequence,2);assert.equal(p.query({traceId:'t'}).length,2);assert.equal(p.verifyIntegrity().valid,true);});
test('duplicate event ids are idempotent',async()=>{const p=new DurableObservabilityPipeline();assert.equal((await p.record({id:'same',type:'execution.started'})).state,'accepted');assert.equal((await p.record({id:'same',type:'execution.started'})).state,'duplicate');assert.equal(p.getSequence(),1);});
test('concurrent memory writes are strictly ordered',async()=>{const p=new DurableObservabilityPipeline();const results=await Promise.all(Array.from({length:50},(_,i)=>p.record({id:'e'+i,type:'execution.progress'})));assert.equal(new Set(results.map(r=>r.event.sequence)).size,50);assert.deepEqual(results.map(r=>r.event.sequence).sort((a,b)=>a-b),Array.from({length:50},(_,i)=>i+1));});
test('file pipeline survives restart and preserves integrity',async()=>{const dir=await mkdtemp(path.join(process.cwd(),'observability-'));const filePath=path.join(dir,'events.jsonl');try{const a=new DurableObservabilityPipeline({filePath,sourceId:'node-a'});await a.init();await a.record({id:'e1',type:'execution.started',executionId:'x'},{traceId:'t1',spanId:'s1'});const b=new DurableObservabilityPipeline({filePath,sourceId:'node-a'});await b.init();assert.equal(b.getSequence(),1);assert.equal(b.verifyIntegrity().valid,true);assert.equal(b.query({executionId:'x'})[0].traceId,'t1');}finally{await rm(dir,{recursive:true,force:true});}});
test('file writers serialize duplicate events',async()=>{const dir=await mkdtemp(path.join(process.cwd(),'observability-'));const filePath=path.join(dir,'events.jsonl');try{const a=new DurableObservabilityPipeline({filePath});const b=new DurableObservabilityPipeline({filePath});await Promise.all([a.init(),b.init()]);const [x,y]=await Promise.all([a.record({id:'same',type:'execution.started'}),b.record({id:'same',type:'execution.started'})]);assert.equal([x,y].filter(r=>r.state==='accepted').length,1);assert.equal([x,y].filter(r=>r.state==='duplicate').length,1);}finally{await rm(dir,{recursive:true,force:true});}});
test('retention does not reset authoritative sequence',async()=>{const p=new DurableObservabilityPipeline({maxEvents:2});await p.record({id:'1',type:'a'});await p.record({id:'2',type:'b'});await p.record({id:'3',type:'c'});assert.equal(p.getSequence(),3);assert.equal(p.checkpoint().firstSequence,2);assert.equal(p.checkpoint().lastSequence,3);});